function trainedNet = trainMyNetwork(XTrain,YTrain,net)
% Define training options
options = trainingOptions('adam', ...
    MaxEpochs=10, ...
    MiniBatchSize=64, ...
    InitialLearnRate=1e-3, ...
    Verbose=false, ...
    Plots='training-progress',...
    Metrics="accuracy");

% Train the network
trainedNet = trainnet(XTrain, YTrain, net, "crossentropy", options);